# Generated by Django 4.2.6 on 2023-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_jptf_id_user_birth_certificate_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_certificate_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Birth Certificate Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nid",
            field=models.IntegerField(blank=True, null=True, verbose_name="NID"),
        ),
    ]
