# Generated by Django 4.2.6 on 2023-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_birth_certificate_number_alter_user_nid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permanent_address",
            field=models.TextField(blank=True, max_length=500, verbose_name="Permanent Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="present_address",
            field=models.TextField(blank=True, max_length=500, verbose_name="Present Address"),
        ),
    ]
